[project]
name = "calibrator"
version = "0.1.0"
description = "Add a short description here"
authors = ["Alvaro <alvgaona@gmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
python = ">=3.12.5,<4"

[pypi-dependencies]
fastapi = { version = ">=0.112.2, <0.113", extras = ["standard"]}
opencv-python = ">=4.10.0.84, <5"
