[project]
name = "calibrator-lambdas"
version = "0.0.1"
description = "All AWS lambdas dedicated to run Calibrator"
authors = ["Alvaro Gaona <alvgaona@gmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64", "linux-aarch64", "osx-64", "win-64"]

[tasks]

[dependencies]
python = ">=3.11.13,<3.14"

[pypi-dependencies]
awslambdaric = ">=3.1.1, <4"
aws-lambda-powertools = ">=3.14.0, <4"

[build-dependencies]
cmake = ">=3.30.3,<3.31"

[feature.test]
dependencies = { ruff = "*", pytest = "*" }

[feature.calibrate]
dependencies = { opencv = ">=4.10.0,<4.11", numpy = ">=2.1.0,<2.2" }
pypi-dependencies = { boto3 = "*" }

[environments]
test = ["calibrate", "test"]
calibrate = ["calibrate"]
