[project]
name = "calibrate"
version = "1.0.0"
description = "An AWS Lambda camera calibration function"
authors = ["Alvaro Gaona <alvgaona@gmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-64", "win-64"]

[tasks]

[dependencies]
python = ">=3.11,<3.12"
opencv = ">=4.10.0,<4.11"
numpy = ">=2.1.0,<2.2"

[pypi-dependencies]
httpx = "*"
awslambdaric = "*"
boto3 = "*"

[build-dependencies]
cmake = ">=3.30.3,<3.31"
